name: Node.js Package

on:
  push:  # This file accesses another server to run this pass on it.
    branches:
      - main  # Can be done in dashes or array style. Be on top of your syntax.
  pull_request:  # Good to do both push and pull. Depending on which branch you are on.
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CHeckout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      #installing npm dependancies
      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          API_KEY: ${{ secrets.MY_API_KEY }}
          # Name/Value is pulled from Github > Settings > Secrets and Value
          run: npm test
